/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoleculesRouteImport } from './routes/molecules'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutoCycleRouteImport } from './routes/auto-cycle'
import { Route as IndexRouteImport } from './routes/index'

const MoleculesRoute = MoleculesRouteImport.update({
  id: '/molecules',
  path: '/molecules',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoCycleRoute = AutoCycleRouteImport.update({
  id: '/auto-cycle',
  path: '/auto-cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auto-cycle': typeof AutoCycleRoute
  '/dashboard': typeof DashboardRoute
  '/molecules': typeof MoleculesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auto-cycle': typeof AutoCycleRoute
  '/dashboard': typeof DashboardRoute
  '/molecules': typeof MoleculesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auto-cycle': typeof AutoCycleRoute
  '/dashboard': typeof DashboardRoute
  '/molecules': typeof MoleculesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auto-cycle' | '/dashboard' | '/molecules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auto-cycle' | '/dashboard' | '/molecules'
  id: '__root__' | '/' | '/auto-cycle' | '/dashboard' | '/molecules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutoCycleRoute: typeof AutoCycleRoute
  DashboardRoute: typeof DashboardRoute
  MoleculesRoute: typeof MoleculesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/molecules': {
      id: '/molecules'
      path: '/molecules'
      fullPath: '/molecules'
      preLoaderRoute: typeof MoleculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-cycle': {
      id: '/auto-cycle'
      path: '/auto-cycle'
      fullPath: '/auto-cycle'
      preLoaderRoute: typeof AutoCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutoCycleRoute: AutoCycleRoute,
  DashboardRoute: DashboardRoute,
  MoleculesRoute: MoleculesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
